# Generated by Django 5.0.6 on 2026-06-26 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AITrainingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('chatgpt', 'ChatGPT'), ('image_gen', "Génération d'images (DALL·E / Midjourney)"), ('tts', 'Texte vers parole (TTS)'), ('content', 'Création de contenu'), ('assessment', 'Évaluation & Quiz'), ('other', 'Autre')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='ai_training_thumbs/')),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], default='beginner', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vidéo de formation IA',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AIExerciseGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammar_rule', models.CharField(max_length=300, verbose_name='Règle grammaticale')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1')], max_length=5)),
                ('exercise_type', models.CharField(max_length=30)),
                ('prompt_used', models.TextField()),
                ('raw_response', models.TextField()),
                ('exercises_created', models.PositiveSmallIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('linked_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Génération d'exercices IA",
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AITemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('template_type', models.CharField(choices=[('exercise', "Générateur d'exercices"), ('lesson_plan', 'Plan de cours'), ('quiz', 'Quiz'), ('feedback', 'Feedback élève'), ('story', 'Histoire / Dialogue'), ('vocabulary', 'Vocabulaire')], max_length=30)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('all', 'Tous niveaux')], default='all', max_length=5)),
                ('prompt_template', models.TextField(help_text='Use {variable} placeholders')),
                ('example_output', models.TextField(blank=True)),
                ('variables', models.JSONField(default=list, help_text='List of variable names in the template')),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modèle IA',
                'verbose_name_plural': 'Modèles IA',
            },
        ),
        migrations.CreateModel(
            name='ChatbotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Nouvelle conversation', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_messages', models.PositiveSmallIntegerField(default=0)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session chatbot',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant'), ('system', 'Système')], max_length=20)),
                ('content', models.TextField()),
                ('tokens', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_tools.chatbotsession')),
            ],
            options={
                'verbose_name': 'Message chatbot',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrammarCorrectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('corrected_text', models.TextField()),
                ('errors_found', models.JSONField(default=list)),
                ('error_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Correction grammaticale',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='project_gallery/')),
                ('project_url', models.URLField(blank=True)),
                ('tools_used', models.JSONField(default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet enseignant',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
